- hosts: all
  vars_files:
    - hadoop_vars.yml

  tasks:
    - name: "Copy Hadoop Software and jdk"
      copy:
        dest: "/root"
        src: "/root/hadoop_software"

    - name: "Install jdk"
      yum:
        name: "/root/hadoop_software/jdk-8u171-linux-x64.rpm"
        state: present
        disable_gpg_check: yes

    - name: "Check if hadoop is installed"
      command: 
        cmd: "rpm -q hadoop"
      register: rpm_check


    - name: "Install hadoop"
      shell: 
        cmd: "rpm -i /root/hadoop_software/hadoop-1.2.1-1.x86_64.rpm --force"
      when: rpm_check.rc != 0


    - name: "Configure hdfs-site.xml"
      template: 
        dest: "/etc/hadoop/hdfs-site.xml"
        src: "/root/client-hdfs-site.xml"


    - name: "Configure core-site.xml"
      template: 
        dest: "/etc/hadoop/core-site.xml"
        src: "/root/datanode-core-site.xml"

    









      

